include("blocksys.jl")
using .blocksys

A=load_matrix("/home/kuba/Projects/Sem-5/Obliczenia Naukowe/L5/dane/Dane16_1_1/A.txt")
# print(A)
printMatrix(A)
println("\n")
b=load_vector("/home/kuba/Projects/Sem-5/Obliczenia Naukowe/L5/dane/Dane16_1_1/b.txt")
print(b)
println("\n")
# afterA,afterb=Gauss(A,b)
afterA,afterb=Gauss_pivot(A,b)
printMatrix(afterA)
println("\n")
print(afterb)
println("\n")
x=solve_gauss(afterA,afterb)
print(x)
println("\n")
#lu=LU_pivot(A)
#solved_lu=solve_LU(lu,b)
#println(solved_lu)

print(get_b_from_ones("/home/kuba/Projects/Sem-5/Obliczenia Naukowe/L5/dane/Dane16_1_1/A.txt"))
test_solve_Gauss("/home/kuba/Projects/Sem-5/Obliczenia Naukowe/L5/dane/Dane16_1_1/A.txt")
test_solve_Gauss_pivot("/home/kuba/Projects/Sem-5/Obliczenia Naukowe/L5/dane/Dane16_1_1/A.txt")
test_solve_LU("/home/kuba/Projects/Sem-5/Obliczenia Naukowe/L5/dane/Dane16_1_1/A.txt")
#test_solve_LU_pivot("/home/kuba/Projects/Sem-5/Obliczenia Naukowe/L5/dane/Dane16_1_1/A.txt")
